name: "Build"

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    name: Build 
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test

    - name: Publish
      run: dotnet publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Sean Dorff's Audio Visualizer
        path: /home/runner/work/Sean-Dorff-s-Audio-Visualizer/Sean-Dorff-s-Audio-Visualizer/Common/bin/Debug/net5.0/Common.dll
      with:
        name: asd
        path: /home/runner/work/Sean-Dorff-s-Audio-Visualizer/Sean-Dorff-s-Audio-Visualizer/Common/bin/Debug/net5.0/publish/
      with:
        name: 3
        path: /home/runner/work/Sean-Dorff-s-Audio-Visualizer/Sean-Dorff-s-Audio-Visualizer/WasAPI/bin/Debug/net5.0/WasAPI.dll
      with:
        name: 4
        path: /home/runner/work/Sean-Dorff-s-Audio-Visualizer/Sean-Dorff-s-Audio-Visualizer/WasAPI/bin/Debug/net5.0/publish/
      with:
        name: 5
        path: /home/runner/work/Sean-Dorff-s-Audio-Visualizer/Sean-Dorff-s-Audio-Visualizer/Sean Dorff's Audio Visualizer/bin/Debug/net5.0/Sean Dorff's Audio Visualizer.dll
      with:
        name: 6
        path: /home/runner/work/Sean-Dorff-s-Audio-Visualizer/Sean-Dorff-s-Audio-Visualizer/Sean Dorff's Audio Visualizer/bin/Debug/net5.0/publish/